version: '3.3'
services:
  web:
    build:
      context: ./drupal
      dockerfile: ./Dockerfile
    restart: always
    container_name: dahal_drupal9
    depends_on:
      - db
    networks:
      - dahal_network
    ports:
    - 80:80
    - 443:443
    volumes:
      - ./drupal:/opt/drupal
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_DIR=${DB_DIR}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    container_name: mysql_database
    restart: unless-stopped
    networks:
      - dahal_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_database_mgmt
    ports:
    - 8080:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
      - dahal_network

networks:
  dahal_network:
    external: false