version: '3.3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik-non-secure.yml:/traefik.yml:ro
      - ./traefik-data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dahal_network"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SITE_URL}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=user-auth@file"
    networks:
      - dahal_network
  web:
    build:
      context: ./drupal
      dockerfile: ./Dockerfile
    image: dahaltn/drupal9_dahal:latest
    restart: always
    container_name: dahal_drupal9
    depends_on:
      - db
    networks:
      - dahal_network
    # command: composer install --ignore-platform-reqs
    volumes:
      - ./drupal:/opt/drupal
      - ./php:/usr/local/etc/php
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_DIR=${DB_DIR}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dahal_network"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(`${SITE_URL}`)"
#    command: composer install --ignore-platform-reqs
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    container_name: mysql_database
    restart: unless-stopped
    networks:
      - dahal_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_DIR}:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_database_mgmt
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dahal_network"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${SITE_URL}`)"
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
      - dahal_network

networks:
  dahal_network:
    external: true