# This is a basic workflow that is manually triggered

name: digital_ocean_deployment
on:
  push:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        if: success() || failure()
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PW }}
          port: 22
          source: .
          target: ${{ secrets.SETUP_FOLDER }}


      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PW }}
          port: 22
          script: |
            cd ${{ secrets.SETUP_FOLDER }}
            chmod +x build.sh
            sh ./build.sh
#            docker exec dahal_drupal9 composer install

#            chown -R dahaltn:dahaltn /var/www/drupal
#            docker stop dahal_drupal9
#            docker stop dahal_drupal9
#            docker-compose up -d
#            docker exec dahal_drupal9 composer id -n
#            docker exec dahal_drupal9 drush cim -y