# This is a basic workflow that is manually triggered

name: digital_ocean_deployment
on:
  push:
    branches: [main]
  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Create .env
        run: |
          touch .env
          echo MYSQL_USER=${{secrets.MYSQL_USER}} >> .env
          echo MYSQL_PASS=${{secrets.MYSQL_PASS}} >> .env
          echo MYSQL_DIR=${{secrets.MYSQL_DIR}} >> .env
          echo MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} >> .env
          echo MYSQL_HOST=${{secrets.MYSQL_HOST}} >> .env

      - name: change Permission
        run: chmod 600 traefik-data/acme.json
        
      - name: Building Docker
        run: docker-compose up -d
  
