# This is a basic workflow that is manually triggered

name: digital_ocean_deployment
on:
  push:
    branches: [test]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: 138.68.117.43
          username: root
          password: ${{ secrets.DIGI_PW }}
          port: 22
          source: .
          target: /var/www

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 138.68.117.43
          username: root
          password: ${{ secrets.DIGI_PW }}
          port: 22
          script: |
            chmod +x /var/www/test.sh
            chown -R dahaltn:dahaltn /var/www/drupal
            sh /var/www/test.sh