# This is a basic workflow that is manually triggered

name: digital_ocean_deployment
on:
  push:
    branches: [test]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: drupal:latest
    steps:
      - name: checking inside container
        run: |
          ls -la /var/www/html
#      - uses: actions/checkout@main
#
#      - name: Building Docker
#        run: |
#          alias dc=docker-compose
#          docker-compose down
#          docker-compose up -d

#      - name: Composer install
#        run: docker-compose exec web composer install --working-dir ../
#
#      - name: Drush config import
#        run: docker-compose exec web drush cim -y
