# This is a basic workflow that is manually triggered

name: digital_ocean_deployment
on:
  push:
    branches: [main]
  
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Create .env
        run: echo 'MYSQL_PASSWORD=${MYSQL_PASSWORD}' \n\
            'MYSQL_DIR=${MYSQL_DIR}' > .env

      - name: change Permission
        run: chmod 600 traefik-data/acme.json
        
      - name: Building Docker
        run: docker-compose up -d
  
